# Generated by Django 3.1.2 on 2020-11-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interiors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phonenumber', models.CharField(default='', max_length=15, unique=True)),
                ('email_id', models.CharField(default='', max_length=100, unique=True)),
                ('house', models.CharField(default='', max_length=15, unique=True)),
                ('timeline', models.CharField(default='', max_length=15, unique=True)),
                ('work', models.CharField(default='', max_length=15, unique=True)),
                ('budget', models.CharField(default='', max_length=15, unique=True)),
                ('comments', models.CharField(default='', max_length=15, unique=True)),
            ],
        ),
    ]
