# Generated by Django 3.1.2 on 2020-11-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interiors',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
