# Generated by Django 3.1.2 on 2020-10-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packers',
            name='accomdationtype',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='housetype',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='maxprice',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='minprice',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='numberoffloors',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='propertyfloor',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='propertyfor',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='sqft',
        ),
    ]
