# Generated by Django 3.1.2 on 2020-10-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201028_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packers',
            old_name='list_date',
            new_name='date_of_moving',
        ),
    ]
