# Generated by Django 3.1.2 on 2020-10-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201028_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='packers',
            name='email_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='packers',
            name='phonenumber',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
