# Generated by Django 3.1.2 on 2020-10-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201028_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packers',
            name='from_housenumber',
        ),
        migrations.RemoveField(
            model_name='packers',
            name='to_housenumber',
        ),
    ]
