# Generated by Django 3.1.2 on 2020-10-29 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201029_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packers',
            name='date_of_moving',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
