# Generated by Django 3.0.8 on 2020-11-07 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='roommate_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('non-binary', 'NON-BINARY')], max_length=20)),
                ('hometown', models.CharField(max_length=264)),
                ('roomtown', models.CharField(max_length=264)),
                ('language', models.CharField(max_length=264)),
                ('occupation', models.CharField(max_length=264)),
                ('course', models.CharField(max_length=264)),
                ('alcohol', models.CharField(choices=[('yes', 'YES'), ('flexible', 'FLEXIBLE'), ('no', 'NO')], max_length=20)),
                ('smoking', models.CharField(choices=[('yes', 'YES'), ('flexible', 'FLEXIBLE'), ('no', 'NO')], max_length=20)),
                ('food_preference', models.CharField(choices=[('flexible', 'Flexible'), ('strictly veg', 'Strictly Veg'), ('strictly non veg', 'Strictly Non Veg')], max_length=20)),
                ('culinary', models.CharField(choices=[('can', 'CAN'), ('sometimes', 'SOMETIMES'), ('cannot', 'CANNOT')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
