# Generated by Django 3.1.2 on 2020-10-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
        migrations.AddField(
            model_name='listing',
            name='housenumber',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
