# Generated by Django 3.1.2 on 2020-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20201027_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pets',
            field=models.CharField(default='', max_length=200),
        ),
    ]
