# Generated by Django 3.1.2 on 2020-11-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='maxprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='minprice',
            field=models.IntegerField(default=0),
        ),
    ]
